# Generated by Django 5.1.4 on 2026-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='badge',
            field=models.CharField(blank=True, choices=[('bio', 'Βιολογικό'), ('traditional', 'Παραδοσιακό'), ('pdo', 'ΠΟΠ')], max_length=20),
        ),
        migrations.AddField(
            model_name='producer',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='producer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='producer',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producer',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='producer',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
