# Generated by Django 5.1.4 on 2026-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_producer_badge_producer_cover_url_producer_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='agroverify_id',
            field=models.CharField(blank=True, help_text="Εθνικός κωδικός εγγραφής στο σύστημα Agro-Verify (ΥΠΨηΔ/ΥΠΑΑΤ). Άδειο όσο το API δεν είναι ακόμη διαθέσιμο — εμφανίζεται badge 'Ready'.", max_length=32),
        ),
    ]
