# Generated by Django 5.1.4 on 2026-04-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_label',
            field=models.CharField(blank=True, help_text="Optional display label e.g. '500γρ', '750ml'", max_length=24),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
