# Generated by Django 5.1.4 on 2026-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='agroverify_code',
            field=models.CharField(blank=True, help_text='Μοναδικός κωδικός Agro-Verify ανά παρτίδα (κρατικό σύστημα ιχνηλασιμότητας ΥΠΨηΔ/ΥΠΑΑΤ). Άδειο όσο το API δεν είναι ακόμη διαθέσιμο.', max_length=64),
        ),
    ]
